name: Criar release e arquivo .tar.gz

env:
  PACKAGE_NAME: chili-void-bspwm-skel.tar.gz
  VERSION: ${{ steps.time.outputs.time }}  # Usando a saída do passo que obtém a hora

# Gatilhos para o workflow
on:
  push:
    branches:
      - main

  workflow_dispatch:  # Permite a execução manual do workflow
    inputs:
      debug_enabled:  # Input para habilitar o modo de depuração
        type: boolean
        description: 'With TMATE'
        required: false
        default: false

  schedule:  # Executa automaticamente toda sexta-feira às 05:00
    - cron:  '0 5 * * 5'

  repository_dispatch:  # Permite a execução através de eventos de webhook
    types:
      - webhook
      - '**'

# Jobs do workflow
jobs:
  # Job para obter a hora atual
  get-time:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.time.outputs.time }}  # Saída do job
    steps:
      - name: Obter a hora atual
        id: time
        run: echo "::set-output name=time::$(date +'%Y%m%d%H%M%S')"

  # Job para preparar a release
  prepare-release:
    runs-on: ubuntu-20.04  # Define a máquina virtual a ser usada
    steps:
      - id: time
        uses: nanzm/get-time-action@v1.1  # Ação para obter o tempo atual
        with:
          format: 'YYYY-MM-DD_HH-mm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}  # Saída do job

 # Job para construir a release
  build:
    runs-on: ubuntu-latest
    needs: [prepare-release]  # Depende do job prepare-release
    strategy:
      matrix:
        package: [$PACKAGE_NAME] # Define o nome do pacote

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Criar arquivo .tar.gz
      run: tar -czf $PACKAGE_NAME .

    - name: Salvar arquivo .tar.gz como artefato
      uses: actions/upload-artifact@v2
      with:
        name: arquivos
        path: $PACKAGE_NAME

    - name: Criar release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
      with:
        tag_name: $VERSION
        release_name: Release $VERSION
        body: |
          Descrição do release aqui.
        draft: false
        prerelease: false

    - name: Fazer upload do arquivo .tar.gz no release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./$PACKAGE_NAME
        asset_name: $PACKAGE_NAME
        asset_content_type: application/gzip
